# Version catalog converted from buildSrc/src/main/kotlin/Dependencies.kt

[versions]
kotlin = "2.2.0"
agp = "8.11.1"
compose = "1.8.2"
coroutines = "1.10.1"
okio = "3.10.2"
kotlinxDatetime = "0.7.1"
kotlinxImmutable = "0.4.0"
multiplatformSettings = "1.3.0"
evas = "1.3.0"
sqldelight = "2.1.0"
atomicFu = "0.29.0"
androidxCoreKtx = "1.13.1"
androidxActivityCompose = "1.9.3"


[libraries]
# kotlinx-coroutines
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
sqldelight-gradlePlugin = { module = "app.cash.sqldelight:gradle-plugin", version.ref = "sqldelight" }

androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivityCompose" }

# Evas
evas = { module = "io.sellmair:evas", version.ref = "evas" }
evas-compose = { module = "io.sellmair:evas-compose", version.ref = "evas" }

kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-composeCompilerPlugin = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
compose-gradlePlugin = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "compose" }
atomicFu-gradlePlugin = { module = "org.jetbrains.kotlinx:atomicfu-gradle-plugin", version.ref = "atomicFu" }
